### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by awps** [aristath/ariColor#4]
Hi.

You should create releases. This will allow installing the desired version via Composer and will automatically install the latest version if not manually specified.

Right now the only way to install it is to manually add the `dev-master` version in composer.json. It does not allow to install the package from command line. I personally prefer to use the CLI.

BTW:
```json
{
    "name": "random/project",
    "require": {
        "aristath/ari-color": "dev-master",
    }
}
```

**Comment by yarri** [comment]
Hi @aristath,

It would be fine if you create a release. The missing release makes it difficult to install ariColor using the Composer.

To create a release just add a version tag:

```
git tag v1.0
git push --tags
```

**Comment by aristath** [comment]
Done (y)
